# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# 
# Let us list the factors of the first seven triangle numbers:
# 
#      1: 1
#      3: 1,3
#      6: 1,2,3,6
#     10: 1,2,5,10
#     15: 1,3,5,15
#     21: 1,3,7,21
#     28: 1,2,4,7,14,28
# 
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five hundred divisors?
import math
def n_fac(n):
  r = 1
  for i in xrange(1, n):
    if n%i==0:
      r+=1
  return r

x = 1
m = 0
nextNum = 1
while 1:
  if m > 500:
    print x
    break
  nextNum += 1
  x+=nextNum
  n = n_fac(x)
  if n > m:
    m = n
    print x, m